
CREATE ROLE wsa_admin
WITH
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    INHERIT
    LOGIN
    NOREPLICATION
    NOBYPASSRLS
    CONNECTION LIMIT 1
    PASSWORD '__WSA_ADMIN_PASS__';

GRANT USAGE
ON SCHEMA wsa
TO wsa_admin;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES
IN SCHEMA wsa
TO wsa_admin;

CREATE ROLE wsa_writer
WITH
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    INHERIT
    LOGIN
    NOREPLICATION
    NOBYPASSRLS
    CONNECTION LIMIT 20
    PASSWORD '__WSA_WRITER_PASS__';

GRANT USAGE
ON SCHEMA wsa
TO wsa_writer;

GRANT SELECT, INSERT, UPDATE
ON ALL TABLES
IN SCHEMA wsa
TO wsa_writer;

CREATE ROLE wsa_reader
WITH
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    INHERIT
    LOGIN
    NOREPLICATION
    NOBYPASSRLS
    CONNECTION LIMIT 20
    PASSWORD '__WSA_READER_PASS__';

GRANT USAGE
ON SCHEMA wsa
TO wsa_reader;

GRANT SELECT
ON ALL TABLES
IN SCHEMA wsa
TO wsa_reader;

